### ISSUE TITLE
Always treat args value wrapped in quotes as a string

### ISSUE THREAD

**Issue by sorentwo** [oban-bg/oban_web#98]
> It would be nice if when manually adding quotes you enforce searching by string. This is not breaking for us, it would just be nice to have it work :)

The value for a query like `args.some_id:"12345"` should be the string `"12345"`, not the number `12345`.

**Comment by iujames** [comment]
It looks like this works, but only when you manually adjust the search term in the address bar to add the quotes. If I type a filter like `args.account_id:"123"` in the filter bar and press enter, it appears to strip off the quotes and search for `account_id:123` (integer instead of string) - is there a way to make my typed in search value preserve the quotes?

**Comment by sorentwo** [comment]
@iujames There's a way now, after [8f4d40f](https://github.com/oban-bg/oban_web/commit/8f4d40f65fb77941746994aa05f84573b06227e5) 🙂

**Comment by iujames** [comment]
Thanks @sorentwo !
